### ISSUE TITLE
Should the expand function allow for undefined?

### ISSUE THREAD

**Issue by silverlight513** [bramstein/url-template#19]
I'm using this module on a variable that will be a string but sometimes due to bad data, the string could be `undefined`. The module currently throws the following error when trying to expand a variable that was parsed with undefined `Cannot read property 'replace' of undefined`.

Instead of doing `urlTemplate.parse(item.url || '')` every time the module is used, it would be good if there was a default value of an empty string so no errors are thrown.

Here's the error reproduced:
https://runkit.com/59106f7a0c1a3d00124401b6/591077f93ae0c30012649458

**Comment by bramstein** [comment]
That sounds like an improvement. Happy to accept a pull request for it. Thanks!

**Comment by jonkoops** [comment]
IMHO it is not up to the library to ensure that values passed into it are indeed valid arguments, that is the responsibility of the consumer. If you are looking for a way to deliver guarantees about the correctness of your code at compile time then TypeScript can help you catch these cases where it does occur.

Since there has also not been a PR created to resolve this issue I am closing it.
