### ISSUE TITLE
Transpile to CommonJS

### ISSUE THREAD

**Issue by rtlayzell** [bramstein/url-template#65]
I'm just wondering, is there a reason you're not transpiling a CommonJS version of the package and offering both CJS and ESM? It's making it very difficult, nay, impossible to create downstream "dual packages". 😢

**Comment by jonkoops** [comment]
This is done on purpose. Shipping only in the ES module format allows us to no longer have to maintain a build system, which reduces the cost of maintenance.

Sadly, the interoperability story in Node.js means you can only effectively use CommonJS imports in ESM, but not the other way around. There is not much we can do about that since that is the direction the Node.js team decided to take, based on (AFAIK) technical limitations.

My advice is to convert any downstream packages to  a [pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), and give them a major version bump. If this is not an option, then you can continue to use the v2 version of this package, although it is no longer under active development.
